packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
  next15:
    "next": 15.0.4
  deps:
    lucide-react: ^0.451.0
  dev-deps:
    eslint: ^9.13.0
    typescript: ^5.6.3
    "@types/node": ^22
    "@types/eslint": ^8
    tailwindcss: ^3.4.1
    postcss: ^8
    autoprefixer: ^10
    postcss-load-config: ^6