packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
  next15:
    "next": 15.0.4
    "@clerk/nextjs": 6.8.0
  deps:
    lucide-react: ^0.451.0
    "@t3-oss/env-nextjs": ^0.11.1
    zod: ^3.23.8
    "@tanstack/react-query": ^5.62.3
    "@tanstack/react-query-devtools": ^5.62.3
  dev-deps:
    eslint: ^9.13.0
    typescript: ^5.6.3
    "@types/node": ^22
    "@types/eslint": ^8
    tailwindcss: ^3.4.1
    postcss: ^8
    autoprefixer: ^10
    postcss-load-config: ^6
    "@0no-co/graphqlsp": ^1.12.16
    "@graphql-codegen/cli": ^5.0.3
    "@graphql-codegen/schema-ast": ^4.1.0
    "@graphql-typed-document-node/core": ^3.2.0
    "@parcel/watcher": ^2.5.0

    