import type { Metadata } from "next";
import { AppProviders } from "@repo/shared/app-providers";
import { mono, sans } from "@repo/ui/fonts";
import "@repo/ui/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProviders>
      <html lang="en">
        <body
          className={`${sans.variable} ${mono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </AppProviders>
  );
}
